default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.3.0'
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v2.35.0'
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.3'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
      - id: yapf
        additional_dependencies: [toml]
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.1.0'
    hooks:
      - id: pyupgrade
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: 'v0.6.13'
    hooks:
      - id: cmake-format
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v14.0.6'
    hooks:
      - id: clang-format
        'types_or': [c++, c, c#, cuda, java, objective-c, proto]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 'v3.5.1-1'
    hooks:
      - id: shfmt
        args: ['-w', '-i', '2', '-s', '-l', '-ci']
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: '5.1.0.1'
    hooks:
      - id: buildifier
      # - id: buildifier-lint
  # - repo: https://github.com/nvuillam/npm-groovy-lint
  #   rev: 'v9.5.0'
  #   hooks:
  #     - id: format-npm-groovy-lint
  #     - id: fix-npm-groovy-lint
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: '0.13.2'
    hooks:
      - id: sqlfluff-fix
      - id: sqlfluff-lint
  - repo: local
    hooks:
      # - id: skywalking
      #   name: skywalking
      #   types: [java]
      #   language: system
      #   entry: license-eye -c .licenserc.yaml header fix
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
      # - id: google-java-format
      #   name: google-java-format
      #   files: \.java$
      #   stages: [commit]
      #   language: system
      #   entry: google-java-format -replace --skip-javadoc-formatting

  - repo: https://github.com/johann-petrak/licenseheaders
    rev: 'v0.8.8'
    hooks:
      - id: licenseheaders
        types_or:
          [c++, c, java, python, rust, cmake, bazel, go, ruby, rust, proto]
        args:
          - '--tmpl=config/codestyle/apache-2.tmpl'
          - '--owner=curoky(cccuroky@gmail.com)'
          - '--settings=config/codestyle/license-settings.json'
          - '--projname=my-own-x'
          - '--projurl=https://github.com/curoky/my-own-x'
          - '--years=2018-2022'
          - '--files'
