name: Unittest

on:
  push:
    paths:
      - '.github/workflows/unittest.yaml'
      - 'tutorial/**'
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  build-with-bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
      - uses: actions/checkout@v2

      - run: earthly --ci +build
        working-directory: tutorial/build-with-bazel
