name: Unittest

on:
  push:
    paths:
      - '.github/workflows/unittest.yaml'
      - 'tutorial/**'
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  build-with-bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
      - uses: actions/checkout@v2

      - name: mount conan cache
        uses: actions/cache@v3
        with:
          path: ~/.conan/data
          key: conan-${{ runner.os }}-${{ hashFiles('conanfile.txt') }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          verbose: 2
          key: conan-ccache-${{ github.run_id }}-${{ github.sha }}
          restore-keys: |
            conan-ccache-

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64

      - name: Install tools
        run: brew install llvm gperf go-task/tap/go-task cmake ninja thrift

      - uses: actions/checkout@v3

      - name: Install conan
        run: brew install conan

      - name: install conan package
        run: task conan

      - name: setup buildbuddy
        run: |
          echo 'build --bes_results_url=https://app.buildbuddy.io/invocation/' >> .bazelrc
          echo 'build --bes_backend=grpcs://remote.buildbuddy.io' >> .bazelrc
          echo 'build --remote_cache=grpcs://remote.buildbuddy.io' >> .bazelrc
          echo 'build --remote_timeout=3600' >> .bazelrc
          echo 'build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API }}' >> .bazelrc

      - name: bazel build
        run: bazel build --remote_download_minimal --jvmopt="-Xmx:8G" --jvmopt="-Xms:512m" //lang/cpp/... || echo error

      - name: bazel test
        run: bazel test //lang/cpp/... || echo ignore error

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
